### ISSUE TITLE
Colocar notificação antes da data de expiração

### ISSUE THREAD

**Issue by taniaa** [pythonbrasil/associados#119]
Criar um robô para lembrar o associado sobre o status de sua associação.

Sugestões de datas para os avisos:
* 2 meses antes de expirar
* 1 mês antes de expirar
* 15 dias antes de expirar

Hoje só recebemos a notificação no dia que expira às 18h!
"""
Olá FULANO,

Gostaríamos de informá-lo que a anuidade referente à sua associação venceu hoje 18 de Agosto de 2015.

Você pode renová-la a qualquer momento. Para isso é só seguir o link abaixo:

associados.python.org.br/xxxxxxxx

Vale lembrar que apenas os membros em dia com sua anuidade podem participar das assembleias da Associação Python Brasil bem como outros direitos garantidos a todos os membros (ex. descontos para inscrições de eventos organizados pela associação).

Caso você já tenha efetuado o pagamento pedimos que desconsidere esse aviso.

Caso tenha alguma dúvida é só entrar em contato conosco através do e-mail: contato@python.org.br.

Obrigado, Equipe da Associação Python Brasil

PS. O sistema de controle de associados está em fase de implantação. Caso encontre algum problema pedimos a gentileza de nos avisar através do mesmo endereço de e-mail: contato@python.org.br.
""" 

PS: o sistema é feito em Django, acredito que muitos possam ajudar.

**Comment by lskbr** [comment]
Tânia, já existe algo asism no sistema. Eu posso atualizar o período e a mensagem, mas já existe. Este ano que recebi 2 mensagens para pagar.

**Comment by lskbr** [comment]
Não consigo dar o assign nesta issue.

**Comment by taniaa** [comment]
Como falei, só vi uma notificação: no dia que expira e tarde (às 18h).

Vou ver seu acesso...

**Comment by lskbr** [comment]
Ok, o alerta é enviado como um comando em:
payment/management/commands/renewal_alert.py
O período hoje é 30, 15 e 7 dias. Vou mudar para 60, 30, 15, 7. O sistema também envia uma mensagem no dia do vencimento.

**Comment by lskbr** [comment]
Alterado.
