### ISSUE TITLE
Atualizar perfil está quebrado para quaisquer dados

### ISSUE THREAD

**Issue by lucasicf** [pythonbrasil/associados#120]
Autenticar-se e acessar http://associados.python.org.br/members/update/
Tentar "Enviar" os dados atuais (não precisa modificar).

Dá erro de categoria não preenchida (mesmo que haja uma antes, ele volta com o campo em branco).

**Comment by lskbr** [comment]
Tinha esquecido desse. Vou olhar.

**Comment by luanfonceca** [comment]
Eu vou pegar essa issue pra um trabalho da minha faculdade. Hoje a tarde resolvo, beleza?!

**Comment by cadu-leite** [comment]
@luanfonceca fechou essa issue ?? Porque acabei de dar update no meu profile .

**Comment by luanfonceca** [comment]
Fala @cadu-leite não fechei não, tentei atualizar no meu e deu erro, pode ser algum bug que só aconteça com Estudante.

**Comment by lskbr** [comment]
Resolvido no branch django 1.8.
