### ISSUE TITLE
Erro cadastro novo alteração de categoria com pedido pendente.

### ISSUE THREAD

**Issue by ulissesathanasio** [pythonbrasil/associados#123]
Reportando erro em cadastro no apybr:
Fui realizar um cadastro novo e marquei como estudante preenchi os dados e fui até a tela de login do pagseguro, porém mudei de idéia e voltei pelo browser mesmo a ficha anterior e alterei para efetivo, cliquei em enviar e foi exibido o aviso de que não seria possível alterar a categoria com um pagamento pendente, porém ele também não permite que volte a categoria original estudante ficando travado no formulário.

**Comment by filipecifali** [comment]
Desculpe a demora pra te dar um retorno nisso Ulisses, existe uma issue referente a isso que impede a modificação do tipo caso haja alguma pendência financeira no cadastro após ser gerada a associação do membro. Como teu usuário já está ativo agora, deves conseguir modificar o tipo dele.
