### ISSUE TITLE
Update Django para >=1.8

### ISSUE THREAD

**Issue by cadu-leite** [pythonbrasil/associados#124]
Django == 1.5

A versão do Django utilizada está ficando velha demais pra manter. 
traçar um plano de backup, 
e começar a pensar em quando poderíamos migrar para a versão mais recente.

**Comment by lskbr** [comment]
Já temos o site rodando na 1.8. Tem um branch para isso e para algumas
melhorias que fiz, mas ainda não acabei. Se alguém quiser ajudar melhor
ainda.

**Comment by cadu-leite** [comment]
Então acho que podemos abrir issues do que está faltando no branch 1.8 e colocar tags (ex.: dj18) para gerir o dev. ...  depois disso podemos invalidar essa issue .

**Comment by lskbr** [comment]
A migração para 1.8 já foi concluída. São as melhorias que ainda estão 
sendo feitas.
No caso, o que falta é a integração de um componente que usa uma base de 
dados de cidades, pois hoje cidade é campo livre.
Tem também vários erros que foram reportados esta semana, não sei se já 
estão todos no Github.

Precisa de alguém para fazer o deployment no Heroku.

Nilo

**Comment by cadu-leite** [comment]
Se a migração foi concluida porque não foi pro master. ou falta atualizar o requirements .

migração ok ?

**Comment by cadu-leite** [comment]
Não da pra entener que a 1.8 está ok. 
então antes de tentar fazer deploy....

1. Colocar o branch da 1.8 no master
1. Data migration
1. homologar

e deploy. precisa no mínimo abrir issues para 1.8
E essas melhorias?

Que tal eu abrir um milestone ?

**Comment by lskbr** [comment]
Pronto para testar a migração. Precisamos de um heroi para testar no Heroku.

**Comment by taniaa** [comment]
Esta issue não concluiu?
