### ISSUE TITLE
Data migration

### ISSUE THREAD

**Issue by cadu-leite** [pythonbrasil/associados#126]
Preparar esquema de migração de dados para Milestone da 1.8

**Comment by lskbr** [comment]
Cadu, as migrações foram criadas a partir do banco atual. Precisamos testar, mas acredito que funcione corretamente, pois iniciei o desenvolvimento com um backup real do banco.

**Comment by cadu-leite** [comment]
beleza. vamos fazer um server de homolog e tentar rodar o pagto. se rolar agente migra. o que acha ? ... posso arranjar este server

**Comment by filipecifali** [comment]
A migração foi realizada já, tenho 3 backups de antes dela qualquer coisa, mas a princípio todas as migrations já estavam preparadas e funcionaram (foram rodadas). 

Se for algo referente ao outra coisa, especifica melhor que eu testo (tenho uma outra conta no associados que está com perfil antigo de estudante que dá pra usar).
