### ISSUE TITLE
Não pode mudar categoria (estudante/..) se houver pagamento pendente

### ISSUE THREAD

**Issue by cadu-leite** [pythonbrasil/associados#127]
porque essa regra ?

```
def clean_category(self):
    category = self.cleaned_data['category']
    if self.instance.id:
        if not self.instance.get_payment_status():
            if self.instance.category != category:
                raise forms.ValidationError(_("You can't change your category with pending payments"))
    return category
```

Não tem um jeito de logar e cancelar ?
tem algum problema com regras do _pag_seguro_ ?

**Comment by filipecifali** [comment]
Não existe motivo para esta regra, atualmente não temos renovação automática. 

Podemos arrancar fora ela!

**Comment by filipecifali** [comment]
https://github.com/pythonbrasil/associados/issues/79 

Está ai a origem da modificação

**Comment by cadu-leite** [comment]
Então , tiramos a regra ?  acho que sim. Alguém contra?

**Comment by fernandogrd** [comment]
Isso é um problema, tive que pedir pra mudarem no banco pro meu caso. Acho mais válido remover a  regra e ter uma experiência melhor pro usuário até que seja implementada uma solução melhor (como em caso de mudança, fazer a cobrança proporcional)

**Comment by fernandogrd** [comment]
Hum, vi agora e não tenho certeza se esse era meu caso, mas lembro de ter tido problemas no passado

**Comment by ocarneiro** [comment]
Eu acho que a regra deve sair. Ela parte de uma desconfiança: "alguém pode tentar se aproveitar e eu preciso me proteger". Acho que podemos assumir boa fé e construir uma comunidade baseada em confiança.

**Comment by filipecifali** [comment]
Eu também não acho que a regra seja muito útil, não existe forma de upgrade atual correta então basicamente o usuário precisaria pagar como estudante para poder alterar para efetivo e ficaria por 1 ano com o status errado, até mesmo impedido de votar na assembléia.
