### ISSUE TITLE
campo location ??  

### ISSUE THREAD

**Issue by cadu-leite** [pythonbrasil/associados#129]
pra que serve o campo _location_ no form de signup ou de perfil ?

me parece que depois do uf/municipio está vazio. podia substituir por _país_.

**Comment by gilsondev** [comment]
Esse campo de UF e municipio aqui, por exemplo não retorna nada.

![Uploading Captura de tela de 2015-11-29 19-16-43.png…](Sem estado e municipio)

Não seria interessante uma abordagem mais simples? O municipio ser preenchido manualmente e listar somente os estados? Assim não iria precisar do widget que foi criado para isso.

**Comment by cadu-leite** [comment]
não sei onde esta testando, mas os campos retornam sim. 
e está gravando.  e se for pra gravar quaquer coisa como municipio melhor tirar. Isso é o que acontece com o campo _location_.

Digo qualquer coisa, porque se for pra cada um digitar o município sem as opções, vamos ter 3 ou 4 grafia diferentes para cada município (com ascento, sem ascento, abreviado....) e  na minha cartilha de dados, isso  = [] (nada)

E o widget é um projeto antigo que é usado por muitos outros projs.

**Comment by gilsondev** [comment]
Estranho, porque aqui não mostrou. Segui conforme o README do projeto. Falta fazer alguma coisa?

**Comment by lskbr** [comment]
O location servirá apenas para a migração, pois o campo novo estará em
branco. Aguardar o fim da migração antes de apagá-lo.

O preenchimento é via Ájax. A última versão no branch tem uma migração que
inicializa os municípios. Se não está OK, favor olhar no banco se os dados
estão lá ou no log do browser para saber se deu erro no js.

Nilo

**Comment by gilsondev** [comment]
Eu vou dar uma olhada com mais afinco nesse problema. Se eu ver alguma coisa estranha, aviso a vocês.

**Comment by cadu-leite** [comment]
Na verdade disvirtuamos a ISSUE. 
A discussão er pra retirada do campo __localtion__ .
quanto a problemas no campo __municipio__ do member, abrir outra issue. 

Podemos fechar essa ?

**Comment by lskbr** [comment]
Location será removido após a migração. Depois poderemos criar mais campos
pra suporta r endereços no exterior. Não pode remover agora para não perder
a informação que temos hoje (cidade e estado). Esse procedimento é manual.

**Comment by cadu-leite** [comment]
Então vou fechar essa issue e abrir uma outra pra ser retirado após a migração. essa fica como inválida
