### ISSUE TITLE
Lançar a versão do branch 1.8 em produção

### ISSUE THREAD

**Issue by lskbr** [pythonbrasil/associados#136]
- Colocar o branch da 1.8 no master
- Data migration
- Preparar o deploy no  heroku
- Homologar
Continuação da #124

**Comment by filipecifali** [comment]
Hoje a app na Heroku está configurada como Heroku-git para deploy, seria mais eficiente para nós configurarmos como uso do próprio repositório git aqui não? 

O dono da app lá está como webmaster@python.org.br, mas acredito ser mais fácil e transparente para a comunidade controlarmos por aqui o acesso ao código dos associados.

De qualquer forma, caso não tenha nenhum impedimento antes, dia 09/07 (sábado agora) irei realizar o merge após rodar os testes locais e cruzar os dedos (com backups antes da migração).

**Comment by luzfcb** [comment]
@lskbr acho que depois que migrar para 1.8, seria bom atualizar todas as dependências, e talvez habilitar nesse repositório, o https://pyup.io/.

https://pyup.io/ é um serviço de um amigo, que manda um pull-request com a atualização das dependências e o respectivo changelog (quando houver)
Exemplo: https://github.com/pyupio/pyup/pull/80

**Comment by lskbr** [comment]
Tem muita coisa para atualizar no front-end também. Acho que ainda usamos
bootstrap 2 e realmente várias dependências bem antigas.


2016-07-11 18:38 GMT+02:00 Fábio C. Barrionuevo da Luz <
notifications@github.com>:

**Comment by filipecifali** [comment]
Merge realizado com o master e deploy realizado.
