### ISSUE TITLE
Atualizar a versão da bootstrap do site

### ISSUE THREAD

**Issue by lskbr** [pythonbrasil/associados#141]
O site usa bootstrap 2, verificar se já não é tempo de migrar para 3 ou 4.
A 3 está entrando em fim de vida (suporte).

**Comment by vmesel** [comment]
@lskbr algum avanço nisso? gostaria de trabalhar neste repositório para podermos adiantar o desenvolvimento da Python Brasil!

**Comment by vmesel** [comment]
@filipecifali há necessidade do Bootstrap ser local? Poderiamos usar a versão cacheada em CDN para poder facilitar o carregamento para as pessoas!

**Comment by filipecifali** [comment]
Não é obrigatório ser local não, não sei porque foi criado assim, pode jogar pro CDN.

PS.: Talvez a versão local seja para faciltiar o desenvolvimento local sem rede.

**Comment by valdergallo** [comment]
Fiz local porque tinha medo de quebrar o layout  :cry:

**Comment by lskbr** [comment]
Oi, eu sou só o reporter. Não estou fazendo isso. Nada contra usarem CDN. Como a manutenção é lenta, sugiro implementar a atualização já na última versão do Bootstrap. Quem estiver trabalhando na issue não esqueça de dar assign (só o vmesel está assigned hoje).

**Comment by filipecifali** [comment]
@valdergallo não tem nenhum problema ter sido feito assim, só não sabiamos o motivo.

**Comment by fmondaini** [comment]
Já tem alguém tocando isso?

**Comment by filipecifali** [comment]
@fmondaini a princípio o @vmesel mas pode tacar ficha, EAFP (it's Easier to Ask Forgiveness than Permission) :smile:

**Comment by fmondaini** [comment]
Acho que o jeito é migrar da V2 pra V3 e então de V3 para V4.

**Comment by filipecifali** [comment]
Se preferir essa migração assim pode ser, por enquanto a 3 está stable e a 4 alpha ainda.

**Comment by luzfcb** [comment]
bootstrap3 oficialmente não possui mais qualquer atualização de correção e não tem mais qualquer tipo de suporte oficial...

bootstrap4 ainda é alfa...  belo limbo...

#### Guia de migração bootstrap 2 para 3:

http://getbootstrap.com/migration/

ferramenta de migração:
http://upgrade-bootstrap.bootply.com/v3
ou 
http://code.divshot.com/bootstrap3_upgrader/


#### Guia de migração bootstrap 3 para 4:

https://v4-alpha.getbootstrap.com/migration/

ferramenta de migração: http://upgrade-bootstrap.bootply.com/

**Comment by fmondaini** [comment]
@luzfcb estou reescrevendo alguns templates do django pra ficar compatível com a V3. Provavelmente vai existir esse retrabalho quando a V4 for lançada. Faz parte do _trade off_ de usar o bootstrap ¯\_(ツ)_/¯

**Comment by filipecifali** [comment]
Merge no https://github.com/pythonbrasil/associados/pull/151 conforme confirmação do @fmondaini pelo que testamos está tudo OK, o que acham de fecharmos essa issue e criarmos uma de migração pro v4?

**Comment by fmondaini** [comment]
Por mim tudo bem :-)
