### ISSUE TITLE
Migrar projeto para python 3

### ISSUE THREAD

**Issue by jeanmask** [pythonbrasil/associados#143]
Acho que seria interessante migrar o projeto para python3, visto que é a versão 2 será descontinuada em breve alem de ter recursos novos bem interessantes, posso me dispor a faze-lo.

**Comment by filipecifali** [comment]
Apenas algumas considerações:

* verificar dependências que precisem ser atualizadas (provavelmente o lxml vai causar)
* atualizar o runtime do Travis-CI para build https://docs.travis-ci.com/user/languages/python
* atualizar o runtime da Heroku para o Dyno rodando https://devcenter.heroku.com/articles/python-runtimes

**Comment by lskbr** [comment]
Deixa comigo. Travis e Heroku vou precisar da sua ajuda @filipecifali

**Comment by luzfcb** [comment]
@lskbr travis-ci e heroku não tem muito segredo não.
é só mudar a linha
https://github.com/pythonbrasil/associados/blob/master/runtime.txt#L1 para `python-3.5.2`

e https://github.com/pythonbrasil/associados/blob/master/.travis.yml#L4 para `3.5`

**Comment by valdergallo** [comment]
Sobe as mudanças em uma branch separada para a galera ajudar a migrar :smiley:

**Comment by filipecifali** [comment]
Gerado branch python3 para isso então.

BTW, o processo de build e deploy está todo automatizado, então se der algum erro na mudança nem sentiremos o impacto direto na app atual, visto que fizemos isso com o django 1.5 => 1.8

**Comment by filipecifali** [comment]
Galera, quem mais quiser contribuir com a migração, o Travis para ser acompanhado é o mesmo do master, basta ver o branch 'python3'

https://travis-ci.org/pythonbrasil/associados/builds/163040221

**Comment by romulocollopy** [comment]
Estou com o projeto rodando local em Python 3 sem problemas.
Temos algum próximo passo?

**Comment by filipecifali** [comment]
Estou fazendo os últimos ajustes na Heroku para o stagging atual, se tudo rodar ok na app em Python3 poderemos fazer o merge do branch no master e o resto vira automaticamente. 

Não consigo prover um link publico pro build log de lá, mas falta pouco :dango:

**Comment by luzfcb** [comment]
@romulocollopy você conseguiu rodar as migrações usando um banco com os dump de dados do banco de produção?

**Comment by romulocollopy** [comment]
@luzfcb eu zerei o banco e rodei o setup. Quando tentei aplica as migrações ao banco que já estava rodando em python 2, tive problemas na ordem de migrações.
Não tenho o banco de produção, mas acredito que teria que fazer o fake das migrações... ou então cirar as migrações denovo.

**Comment by luzfcb** [comment]
@romulocollopy te chamei no Telegram...

**Comment by romulocollopy** [comment]
#163 é relacionada

**Comment by ramiroluz** [comment]
No README diz para rodar make setup.

Mas ao rodar acontece o seguinte:

associados/associados/settings_local.py", line 4, in <module>
    from settings import *
ImportError: No module named 'settings'
Makefile:5: recipe for target 'setup' failed
make: *** [setup] Error 1

Estou usando python3.4. Django 1.10.

Mudei a linha4 para:

`from .settings import *`

Funcionou o make setup. Mas esse arquivo, settings_local.py está no gitignore, não sei como fazer o pull request. :P

**Comment by cuducos** [comment]
Essa issue pode ser fechada dada #178 ?

**Comment by jeanmask** [comment]
@cuducos creio que sim :)
