### ISSUE TITLE
Sistema de pagamentos

### ISSUE THREAD

**Issue by filipecifali** [pythonbrasil/associados#146]
Essa issue é uma proposta de modificação.

Atualmente o sistema de pagamentos é fixo para o PagSeguro e totalmente mesclado com o código.

O Ideal seria separar a responsabilidade de pagamento com o agende de pagamento, o modelo de Payments para ser ele mesmo uma interface para qualquer tipo de pagamento de outros meios (paypal, pagar.me).

Assim poderiamos adicionar outras formas de pagamento conforme a necessidade e teremos poder de negociação encima de valores de cada tipo de pagamento (de acordo com as taxas de cada serviçol, podemos dar preferência para o serviço mais barato ou com melhor serviço conforme nossa necessidade).

Comentários são necessários e bem-vindos (tanto de sugestões / estratégias quanto de serviços que possam ser adicionados).

**Comment by romulocollopy** [comment]
Estou forcando pra olhar essa issue. Se alguém mais estiiver fazendo o mesmo, por favor me fala :)

**Comment by romulocollopy** [comment]
A gente já sabe qual será o gateway de pagamento novo? Vou avançar nessa issue por essa semana.

**Comment by filipecifali** [comment]
@romulocollopy não ainda, mas ficou claro o escopo da issue? A princípio é remover a dependência de sermos obrigados a receber somente pelo pagseguro do sistema.

**Comment by romulocollopy** [comment]
Sim @filipecifali. Vou tentar deixar o mais genérico possível.

**Comment by romulocollopy** [comment]
Alguém poderia analisar se a #154 resolve essa issue?

**Comment by rougeth** [comment]
Tive que navegar pelo código do pagamento, ficou ótimo @romulocollopy, obrigado!
