### ISSUE TITLE
Problema com URLs do Django

### ISSUE THREAD

**Issue by vmesel** [pythonbrasil/associados#148]
Olá galera, sou novato na Python Brasil e no universo do Django. Gostaria de pedir a ajuda de vocês para resolver o seguitne problema: ao tentar acessar a versão local deste website, eu me deparo com a seguinte home:

![Erro do Django](https://cloud.githubusercontent.com/assets/4984147/18738437/2430b1f6-8072-11e6-8ff4-936b160aa766.png)

E este é meu log de acessos:

```
Performing system checks...

System check identified no issues (0 silenced).
September 22, 2016 - 03:06:26
Django version 1.8.13, using settings 'associados.settings_local'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[22/Sep/2016 03:06:29] "GET / HTTP/1.1" 404 1131
[22/Sep/2016 03:06:29] "GET /favicon.ico HTTP/1.1" 404 1143
[22/Sep/2016 03:06:48] "GET / HTTP/1.1" 404 1131

```

**Comment by filipecifali** [comment]
Qual a distro e forma que esta rodando o projeto?

**Comment by valdergallo** [comment]
Estranho, porque se vc não estivesse logado ele deveria te redirencionar para a página de login por default. 

Veja no associados/settings.py
```
# Security
LOGIN_URL = '/'
LOGIN_URL = reverse_lazy('login')
LOGIN_REDIRECT_URL = reverse_lazy('members-dashboard')
```

Isso poderia acontecer se vc já se logou e tentou acessar o / ... que achei o bug aqui 

b0c69a4e514d98d256a413e609b7e2
```
url(r'^', include('django.contrib.auth.urls')),
```

Mas precisaria fazer mais testes. 

@vmesel Já arruma ai e faz um Pull Request :+1:

**Comment by vmesel** [comment]
@filipecifali é Ubuntu 16.04 LTS

@valdergallo vou fazer!

**Comment by filipecifali** [comment]
@vmesel @valdergallo vocês conseguiram testar pra gerar um PR e fechar essa issue?

**Comment by romulocollopy** [comment]
O app não tem uma "Home", quer dizer, eu não sei o que vai no "/".
Posso criar uma view para redirecionar no login, ou simplesmente configurar o login pra raiz do site.
O que vocês preferem?
