### ISSUE TITLE
Enviar e-mail de boas-vindas do sistema ao novo usuário

### ISSUE THREAD

**Issue by filipecifali** [pythonbrasil/associados#150]
Criar uma mensagem padrão para os membros que se associarem com informações importantes como:

Sites oficiais (site da associação, site do evento, página de grupos locais, etc)
Github da associação 
Link para cadastro na lista apyb-associados
Link para redes sociais
Iniciativas de grupos específicos (scipy, pyladies, djangogirls, etc)
Outras informações pertinentes

Sugiro investigar antes de gerar qualquer código customizado:

http://django-emailtools.readthedocs.io/en/latest/how-to.html

**Comment by cantoniazzi** [comment]
@filipecifali o que você acha da função de envio de e-mails ser uma genérica dentro do app core?
Tipo assim: https://github.com/cantoniazzi/associados/blob/issue%23150/app/core/mail.py

**Comment by filipecifali** [comment]
@cantoniazzi acho que é tranquilo, o propósito do link anterior é dar uma idéia do que fazer, no caso, alterar o save do usuário padrão pra quando ele seja criado, receba as infos, tipo um e-mail de boas vindas.

**Comment by cantoniazzi** [comment]
Belezura! @filipecifali

**Comment by cantoniazzi** [comment]
Tô meio ocupado com umas paradas. Mas assim que der eu concluo essa issue. @filipecifali

**Comment by jamesperes** [comment]
pode fechar =D
