### ISSUE TITLE
API para status dos usuários

### ISSUE THREAD

**Issue by gutomaia** [pythonbrasil/associados#153]
**Objetivo:**

Possibilitar de forma simples que outros sites, relevantes a APYB, saibam o status do usuário.

**Ideia:**

Um endpoint com o email do usuario em MD5 como argumento retornando TRUE || FALSE.

**O que precisa:**

- [ ] Alterar o SAVE do usuário para gravar o MD5 do email de forma canonica (sem CAPS e sem espaços)
- [ ] Uma migração para gerar o MD5 de todos os usuários existentes.
- [ ] Um endpoint que receba um MD5 na url e faça um select no banco do usuário que tenha aquele MD5. O endpoint precisa suportar CORS. Assim tanto o frontend quando o backend podem validar e prover um melhor feedback para o usuário.

**Comment by romulocollopy** [comment]
Oi @gutomaia, tenho uma dúvida: por que precisamos consultar usando o md5 do email?
Para gerar o md5, o cliente da API necessita ter o e-mail do que o membro cadastrou no sistema, o que já anula a privacidade do email.
Me parece mais direto consultar com o email em um parâmetro GET.
Você poderia me dizer que vantagem tem fazer com o MD5?

**Comment by filipecifali** [comment]
@romulocollopy para tentar ser menos explícitos ao trafegar esses dados na internet, reduzindo a chance de um sniffer pegar automaticamente o e-mail consultado. Se usarmos HTTPS e um MD5 na consulta teremos uma boa segurança.

A idéia não é ser anônimo entre APyB <=> Evento e sim pra internet apenas.

**Comment by romulocollopy** [comment]
Entendi @filipecifali. Sabe se já tem alguém atacando essa?

**Comment by filipecifali** [comment]
Acredito que não @romulocollopy 

Quando eu estava gerando a lista de associados que no fim virou só esse carinha aqui https://github.com/pythonbrasil/associados/blob/master/lista_associados.py eu também estava testando o JSONserialize que o @luzfcb tinha comentado mas no fim não segui ele: https://github.com/pythonbrasil/associados/commit/5bc2f663d9afcfa4b55cbc22db8be0f5ec206c1b

**Comment by romulocollopy** [comment]
Fora o md5, esse endpoint faria o que a gente precisa?
http://associados.python.org.br/members/status/?email=romulocollopy@gmail.com

**Comment by filipecifali** [comment]
Acredito que sim, na Heroku vamos precisar adquirir no mínimo 1 dyno pra adicionar o SSL, vou verificar se é possível / vale a pena ou fazemos de outra forma.

**Comment by romulocollopy** [comment]
sei que o cloudflare permite botar SSL no heroku, mas não sei qual o mínimo de dynos:
https://support.cloudflare.com/hc/en-us/articles/205893698-Configure-CloudFlare-and-Heroku-over-HTTPS

**Comment by filipecifali** [comment]
É 1 dyno pra por SSL próprio, eu pessoalmente não gosto da forma como o CloudFlare serve o SSL, pois ele nada mais é do que um Proxy externo com SSL somente até a ponta dele.

**Comment by romulocollopy** [comment]
Eu também não curto muito a Cloudfare não, mas achei que poderia ser o mais simples

**Comment by filipecifali** [comment]
URL associados.python.org.br/api/v1/members/<md5sum>/status

**Comment by rougeth** [comment]
Fechando essa issue, já que a API foi criada. Valeu!
