### ISSUE TITLE
Desacoplar local_settings usando .env

### ISSUE THREAD

**Issue by romulocollopy** [pythonbrasil/associados#156]
Atualmente, ao tentar mudar o sistema de pagamento para diminuir o acoplamento ao PagSeguro, estou com problemas ao usar o local_settings, pois acredito que não devo mudar esse arquivo, já que ele é referente ao ambiente de cada um. 

Porém, usar o `python_decouple` de nosso, posso generalizar o settings e deixar as configurações específicas para um .env, e disponibilizar um .env_example no repositório para servir de modelo para as instalações locais

**Comment by filipecifali** [comment]
Pode modificar sim, só lembrar de dar um update no https://github.com/pythonbrasil/associados/blob/master/README.md também para o novo modo de uso e o requirements.txt.

**Comment by luzfcb** [comment]
Eu estava trabalhando nisso no meu fork, no branch [refatoracao_layout_projeto](https://github.com/luzfcb/associados/tree/refatoracao_layout_projeto
)
Peguei o branch de Python3 que o Nilo fez, fiz rebase para o master e comecei a refatorar para ficar mais ou menos assim (ainda vou aplicar o mesmo layout no meu branch `refatoracao_layout_projeto`):

https://github.com/luzfcb/associados/tree/python3_velho/config/settings


Eu estava tendo alguns problemas com as migrações do django-municipios e as tabelas do banco de produção...

**Comment by romulocollopy** [comment]
Usei um example_settings.ini porque o .env fica oculto e pode gerar confusão.
@luzfcb, poderia olhar a #157 ?

**Comment by romulocollopy** [comment]
solved by #157
