### ISSUE TITLE
Atualizar django_municipios

### ISSUE THREAD

**Issue by romulocollopy** [pythonbrasil/associados#163]
De acordo com o changelog https://docs.djangoproject.com/en/1.10/releases/1.10/, o parâmetro context_instance foi removido na versão 1.10 https://github.com/znc-sistemas/django-municipios/blob/master/municipios/views.py#L22, o que está gerando um erro 500 ao fazer a requisição de municípios na página de update member.

Aproveitando o trabalho do @lskbr para portar para o Python3, abro um PR pro fork dele:
https://github.com/lskbr/django-municipios/pull/1

Após resolvido, vamos checar com o @cadu-leite um PR para o https://github.com/znc-sistemas/django-municipios/, publicar no pip e atualizar a versão nos requirements.

**Comment by vmesel** [comment]
@romulocollopy como está o estado desta migração? Podemos abrir o PR no django-municipios?

**Comment by cadu-leite** [comment]
Por mim, beleza. 
  ...  acho que vale uma tag com a versao atual e atualização no master ! keep it simple.

**Comment by vmesel** [comment]
@romulocollopy será que não conseguimos usar essa lib para poder nos auxiliar com o uso de cidades?https://github.com/coderholic/django-cities
