### ISSUE TITLE
Criar uma api para gerenciamento de membros que vão a eventos da comunidade

### ISSUE THREAD

**Issue by vmesel** [pythonbrasil/associados#164]
A criação de uma API que possibilite o usuário poder colocar seu nome na lista, checar onde será o evento e outras coisas pode facilitar a vida de muitos, além de possibilitar a realização de sorteio de uma forma mais rápida.

Portanto eu sugiro a criação de uma API em que os membros da Python Brasil possam entrar em eventos, configurar seus nomes na lista(devemos checar as políticas com cada grupo regional) e ainda poderiamos fazer a parte de sorteio para os membros. Assim que tivermos bem implantados, podemos passar para todos os grupos regionais.

**Comment by filipecifali** [comment]
Mas ai impediriamos de outros usuários do evento que não são associados de participarem dos sorteios? Parece contra-intuitivo se for dessa forma. 

A issue #153 já resolveria o caso de consultar se o associado está em dia para algum sorteio "exclusivo" para membros, mas não sou a favor dessa forma de uso.

Acredito que a API deva ser usada para validar a associação do membro para algum desconto na entrada do evento no máximo. 

O que acha?

**Comment by vmesel** [comment]
@filipecifali realmente parece contra intuitivo olhando pelo seu argumento. Poderiamos cadastrar "amigos do Python" que seriam o pessoal de eventos que ainda não contribuiram para a associação
