### ISSUE TITLE
Teste com erro app.payment.tests.test_commands.RenewalAlertTest

### ISSUE THREAD

**Issue by filipecifali** [pythonbrasil/associados#166]
======================================================================

FAIL: test_renewal_alert_send_today_email (app.payment.tests.test_commands.RenewalAlertTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/pythonbrasil/associados/app/payment/tests/test_commands.py", line 72, in test_renewal_alert_send_today_email

    self.assertEqual(mail.outbox[3].subject, '[Associação Python Brasil] Anuidade vencida')

AssertionError: '[Associa\xc3\xa7\xc3\xa3o Python Brasil] Aviso de renova\xc3\xa7\xc3\xa3o' != '[Associa\xc3\xa7\xc3\xa3o Python Brasil] Anuidade vencida'

O erro apareceu depois do merge de https://github.com/pythonbrasil/associados/pull/165 mas acredito que o problema não é do PR e sim do teste, porque antes acontecia um comportamento errado (de retornar None sem tratar e o Admin se perdia.

**Comment by vmesel** [comment]
@filipecifali como resolveremos? Colocamos um decode/encode no final do:
```
mail.outbox[3].subject
```
?

**Comment by filipecifali** [comment]
@vmesel as mensagens são diferentes, não é erro de encoding. Uma é Aviso de renovação, outra é Anuidade vencida.

**Comment by filipecifali** [comment]
Removi o teste por enquanto @vmesel se quiser pode alterar o teste e mandar um PR.
