### ISSUE TITLE
Melhorar instrução para config inicial do Postgres

### ISSUE THREAD

**Issue by viniciusban** [pythonbrasil/associados#167]
Mudar as instruções para configuração inicial do Postgres, no `README.md`.

De

```
psql -d postgres
```

Para 

```
su postgres psql -U postgres
```

Na VM Ubuntu, precisei usar esse comando acima porque como está no `README.md` dava o seguinte erro:

```
$ psql -d postgres
psql: FATAL:  role "ubuntu" does not exist
```

**Comment by filipecifali** [comment]
Atualizado: https://github.com/pythonbrasil/associados/blob/master/README.md
