### ISSUE TITLE
Tamanho do banco de dados

### ISSUE THREAD

**Issue by filipecifali** [pythonbrasil/associados#174]
Depois do merge dos municípios acho que alguma coisa não deu certo nas migrações e o db está inflado mais do que o normal. 

Preciso de ajuda de alguém com tempo para mexer no pgsql da app (hospedado na Heroku) 

Hoje nosso status é:

16,596 rows

Precisariamos reduzir para abaixo de 10k para voltar ao plano free

**Comment by elinaldosoft** [comment]
Qual foi objetivo de adicionar os municípios ao database ?

**Comment by filipecifali** [comment]
Veio deste commit para o master: https://github.com/pythonbrasil/associados/commit/4399ff68fba4b7f5c0f7a6c100472815ff8efec1 

Mas não encontrei onde foi tratado ou o porque de ter sido feito, vou procurar mais um pouco no histórico

**Comment by filipecifali** [comment]
Aqui tem um pouco mais de info: https://github.com/pythonbrasil/associados/issues/133

**Comment by lskbr** [comment]
Opa, o banco de dados de municípios tem todos os municípios do Brasil. Então espere no mínimo 5000 registros. Mas o tamanho não deveria ter sido alterado, uma vez que fizemos isso em 2015. O @cadu-leite é o autor do componente, talvez ela já tenha visto algo assim. Uma especulação que faço é uma migração que possa ter adicionado os mesmos dados mais de uma vez.

**Comment by elinaldosoft** [comment]
Verdade, pode ser que o migration duplicou, faz um group by na table, para ver se tem dado duplicado!

**Comment by vmesel** [comment]
@filipecifali talvez uma alternativa seja a gente filtrar por regiões metropolitanas e só deixar estas cidades disponíveis, (sim é um método que causa exclusão, mas talvez seja mais eficiente).

**Comment by filipecifali** [comment]
O Gabriel Oliveira analisou o banco e descobriu que não tem o que fazer pra reduzir o tamanho:

public     | municipios_municipio       |       5572

O que poderia ser feito é mover a base de municípios para um webservice em uma app separada e consultar de lá.

**Comment by luzfcb** [comment]
@filipecifali acho que essa é uma ideia perfeitamente viável...
talvez role de subir esse webservice no google appengine e liberar consultas somente para o dominio do associados, de modo a ficar sempre dentro do quota gratuita...

@renzon tu manja mais sobre o appengine, será que essa ideia é viável?

No google appengine quota gratuita, a maquina "dorme" como no heroku?
Tem MySQL/Postgresql no appengine quota gratuita?

**Comment by filipecifali** [comment]
A App pode ficar na Heroku mesmo em uma app separada, segregar parece mais trabalhoso de gerenciar.

**Comment by luzfcb** [comment]
Será uma app paga no heroku, porque no dyno gratuito tem o tempo de indisponibilidade devido ao tempo que a maquina demora para acordar. (no dyno gratuito, a maquina dorme apos 30 minutos sem acesso)

**Comment by luzfcb** [comment]
Talvez de para fazer um hack com Middleware do django na app associados, para mandar uma requisição para a API, de modo a força-la acordar...

**Comment by filipecifali** [comment]
Pode até ser pago, o Dyno é mais barato que o pgsql deles.

**Comment by renzon** [comment]
@luzfcb já foi fechado. Pelo menos acerca de municipios eu tenho uma app minha bem antiga no App Engine. Assim que tiver um tempo dou uma olhada e posto aqui.
