### ISSUE TITLE
Diferença de benefícios 

### ISSUE THREAD

**Issue by fecaridade** [pythonbrasil/associados#179]
As paginas de associação da python brasil tem benefícios diferentes.   

[associação python brasil](https://associacao.python.org.br/)

* Estudantes
    * Anuidade: R$32,00
* Efetivo
  * Anuidade: R$64,00
  * Direito a votar e ser votado para cargos da APy

[python brasil/apyb](https://python.org.br/apyb/) 

* Estudantes
  * Anuidade: R$32,00
  * Direito a votar em eleições para cidade sede da Python Brasil
* Efetivo
  * Anuidade: R$64,00
  * Direito a votar e ser votado para cargos da APyB
  * Direito a votar em propostas de alteração no estatuto
  * Direito a votar em eleições para cidade sede da Python Brasil

**Comment by barmvicente** [comment]
vou começar essa
