### ISSUE TITLE
Atualizar Dockerfile e docker-compose

### ISSUE THREAD

**Issue by filipecifali** [pythonbrasil/associados#186]
Ambos arquivos estão defasados, atualizar eles pode ajudar na migração para Python3 e facilitar o desenvolvimento local

**Comment by barraponto** [comment]
Tô conferindo o [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) pra evitar aquela gambiarra do `check_db.py`

**Comment by cuducos** [comment]
Vejo que os arquicos estão atualizados (usam Python 3, por exemplo) e quem tem documentação no `README.md` sobre como rodar locamente. O que falta pra essa issue ser fechada?

**Comment by filipecifali** [comment]
@cuducos faltava nada, só não foi fechada mesmo :)
