### ISSUE TITLE
Atualizar Django 1.10 para 1.11

### ISSUE THREAD

**Issue by filipecifali** [pythonbrasil/associados#187]
Precisamos atualizar o Django pois já perdemos suporte de segurança

**Comment by arkanister** [comment]
Eu quero.

**Comment by arkanister** [comment]
Estive mechendo nessa issue, contudo temos bastante dependências depreciadas nesse projeto.

Cada vez que tento avançar caio em um novo problema. Consegui atualizar a versão do Django para 1.11.x sem problemas, mas agora o projeto está quebrando pelo uso das seguintes dependências:

- lxml (minha sugestão é utilizar beautifulsoap).
- django_bootstrap_toolkit (Incompatível com a versão 1.11.x do django).

Vou publicar o avanço que fiz no meu repositório, se alguém tiver afim de ajudar nisso ficaria feliz, pois sozinho não vou ter braço para ajustar tudo.

Outra alternativa, que talvez seja até mais simples seria reescrever o projeto em uma versão mais nova do django, já utilizando python3.x. Acredito que vá dar menos trabalho no final, já poderiam desenhar um template novo também.

Publiquei minhas alterações direto na branch master do meu fork.

https://github.com/arkanister/associados

Fico a disposição para dúvidas.

**Comment by lskbr** [comment]
Que tal atualizar pro 3.x! Casa de ferreiro espeto de pau :-D

**Comment by cuducos** [comment]
Já estamos usando a 1.11 desde #210 — podemos atualizar a _issue_ para atualizar para Django 2 ou 3?

**Comment by filipecifali** [comment]
@cuducos faz sentido atualizar a issue ao invés de criar outra? A meu ver fechamos essa e criamos outra com o próximo objetivo

**Comment by cuducos** [comment]
> A meu ver fechamos essa e criamos outra com o próximo objetivo

Concordo 💜
