### ISSUE TITLE
Corrigir instalação django_bootstrap_toolkit 

### ISSUE THREAD

**Issue by filipecifali** [pythonbrasil/associados#191]
Obtaining django_bootstrap_toolkit-dev from git+https://github.com/pythonbrasil/django-bootstrap-toolkit.git@v1-associados#egg=django_bootstrap_toolkit-dev (from -r requirements.txt (line 7))
  Cloning https://github.com/pythonbrasil/django-bootstrap-toolkit.git (to revision v1-associados) to ./src/django-bootstrap-toolkit-dev
  Running setup.py (path:/usr/src/app/src/django-bootstrap-toolkit-dev/setup.py) egg_info for package django-bootstrap-toolkit-dev produced metadata for project name django-bootstrap-toolkit. Fix your #egg=django-bootstrap-toolkit-dev fragments.

Bonus:

Obtaining django_s3_folder_storage-dev from git+https://github.com/pythonbrasil/django-s3-folder-storage.git@v1-associados#egg=django_s3_folder_storage-dev (from -r requirements.txt (line 12))
  Cloning https://github.com/pythonbrasil/django-s3-folder-storage.git (to revision v1-associados) to ./src/django-s3-folder-storage-dev
  Running setup.py (path:/usr/src/app/src/django-s3-folder-storage-dev/setup.py) egg_info for package django-s3-folder-storage-dev produced metadata for project name django-s3-folder-storage. Fix your #egg=django-s3-folder-storage-dev fragments.

**Comment by patymori** [comment]
Vou tentar resolver esse
