### ISSUE TITLE
Corrigir link de inscrição no template de email para novos membros

### ISSUE THREAD

**Issue by gabubellon** [pythonbrasil/associados#200]
O [arquivo](https://github.com/pythonbrasil/associados/blob/master/app/members/templates/members/email.html) de template para novos membros não está com o link para inscrição na lista de email.

**Comment by tyronedamasceno** [comment]
Vou trabalhar nesta issue. @filipecifali atribui dps

**Comment by tyronedamasceno** [comment]
@gabubellon @filipecifali @mazulo algum de vcs sabe dizer se existe uma lista de e-mail específica para associados ou se é a lista de email da comunidade mesmo?
No caso, essa https://python.org.br/lista-de-discussoes/

**Comment by mazulo** [comment]
@tyronedamasceno existe sim. Não sei exatamente como essa lista funciona (se é de acesso pública e você pode "joinar" a lista, ou se seria por convite). Vou confirmar e atualizo aqui com o link

**Comment by mazulo** [comment]
@tyronedamasceno esse aqui é o link: https://groups.google.com/forum/#!forum/apyb-associados
