### ISSUE TITLE
Sensitive data

### ISSUE THREAD

**Issue by Ajwani97** [pythonbrasil/associados#211]
Hello there,
I was just searching around using an automated scanner and found email leaks and a secret key leak.

If you consider that this is a false positive, please feel free to close this issue.

Please consider an alternative approach, while storing sensitive data, hard coded in files.

Thanks

**Comment by mazulo** [comment]
Hi @Ajwani97. The secret key hard-coded is only used in local development (in production we get it from env vars and the email we have hard-coded is also for local dev purposes. However I'll double check it anyway. Thank you for reporting this.

**Comment by mazulo** [comment]
Solved in #213. Thanks!

**Comment by Ajwani97** [comment]
As a best security practice, is it possible for you to rotate your client keys, as an attacker can clone the repo and find secrets in commits..

If you can, please do, if it's not possible, please let me know where I can help..

Thanks :)
