### ISSUE TITLE
CRITICO: Atualizar app associados da stack Heroku-16 para stack Heroku-20

### ISSUE THREAD

**Issue by luzfcb** [pythonbrasil/associados#216]
Conforme comunicado oficial (https://help.heroku.com/0S5P41DC/heroku-16-end-of-life-faq), a stack [`Heroku-16`](https://devcenter.heroku.com/articles/heroku-16-stack) será descontinuada e as apps devem ser atualizadas para a stack mais recente (nesse momento é a  [`Heroku-20`](https://devcenter.heroku.com/articles/heroku-20-stack)). Apartir de 01 de Maio de 2021 a stack `Heroku-16` parará de receber atualizações de segurança e no dia **01 de Junho** não será mais possivel fazer deploy de apps que a usem, a exemplo da app `associados`.

![image](https://user-images.githubusercontent.com/807599/108757529-b4f48f00-7528-11eb-88a2-d2e5372a3809.png)

Aqui há o guia oficial de migração https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack

https://devcenter.heroku.com/articles/heroku-20-stack

C/C @mazulo @thaisviana

**Comment by luzfcb** [comment]
Tem um botão "Upgrade Stack", mas não tenho ideia do estrago que isso poderia fazer... eu teria cautela 
![image](https://user-images.githubusercontent.com/807599/108759507-32210380-752b-11eb-80d9-01b49e48dabb.png)

**Comment by luzfcb** [comment]
@thaisviana ping

**Comment by thaisviana** [comment]
Eu vou ter que olhar isso na semana que vem.

Em seg., 12 de abr. de 2021 12:56, Fábio C. Barrionuevo da Luz <
***@***.***> escreveu:

**Comment by cuducos** [comment]
Caso isso não tenha sido feito ainda, quem são as pessoas com acesso ao Heroku que podem fazer?

**Comment by cuducos** [comment]
Acredito que o #217 fecha essa issue, não?

**Comment by filipecifali** [comment]
Sim @cuducos
