### ISSUE TITLE
Faz sentido um “requirements” para testes no macOS?

### ISSUE THREAD

**Issue by cuducos** [pythonbrasil/associados#225]
Aparentemente surgiram `requirements_test.txt` e `requirements_test_osx.txt` pq o `readline` não era necessário no Linux (73e15b2ca0a0d10c6c9e90daa0cd9036bf822d9c).

Hoje a única diferença é o `mock` que não tem a ver, aparentemente, com sistema operacional (mas com versão do Python mais antiga do que utilizamos), segundo a [documentação no PyPI](https://pypi.org/project/mock/):

> mock is now part of the Python standard library, available as `unittest.mock` in Python 3.3 onwards.

**Comment by filipecifali** [comment]
Não faz mais não, aprovei o PR e adicionei mais um para revisar junto

**Comment by cuducos** [comment]
Fechado por #226
