### ISSUE TITLE
Juntar settings.py

### ISSUE THREAD

**Issue by cuducos** [pythonbrasil/associados#227]
Vejo que o projeto tem arquivos diferentes de `settings.py` — que tal juntarmos tudo em um `settings.py` só e fazer a diferença entre produção, testes e desenvolvimento ser uma questão de instância (por exemplo, variáveis de ambiente) e não de código?

Posso fazer essa adaptação, e acredito que isso traz alguns benefícios:

* simplificação da instalação (menos parâmetros nos comandos, valores padrões que funcionam para desenvolvimento)
* maior paridade entre código de desenvolvimento e de testes (eles podem ser iguais, avalio)
* maior paridade entre código de produção e demais instâncias

**Comment by filipecifali** [comment]
Acredito que vai ficar bem melhor mesmo dessa forma, tendo valores padronizados que sejam válidos e pegando variáveis de ambiente tudo deve funcionar em um único arquivo mesmo.
