### ISSUE TITLE
Mudança do nome da branch principal?

### ISSUE THREAD

**Issue by cuducos** [pythonbrasil/associados#229]
Esse repositório ou comunidade já cogitou mudar o nome da _branch_ principal de `master` para `main`?

**Comment by mazulo** [comment]
Durante a gestão passada, a mudança foi cogitada (que seria seguida a mudança do repo do sistema dessa org aqui para a org da APyB), mas depois acabou não indo pra frente (faltou mãos). Acho que agora o caso pode ser bem diferente :)

**Comment by rougeth** [comment]
Feito! \o/
