### ISSUE TITLE
Atualizar versão do Python para >=3.7

### ISSUE THREAD

**Issue by muriloviana** [pythonbrasil/associados#236]
Aparentemente o site atual está rodando em Python 3.6.9, porém essa versão não é mais suportada. Dito isso, seria muito bem-vindo atualizarmos a versão do Python para no mínimo 3.7.

**Comment by luzfcb** [comment]
Sugestão, atualizar a base de codigo para python3.9+:

1 - `mkvirtualenv -p python3.9 associados3.9`
2 - `python3 -m pip install pyupgrade pre-commit`
3 - 
```bash
cat > .pre-commit-config.yaml <<'_EOF'
repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        args: ['--py3-plus', '--py39-plus']
_EOF
```

4 - `pre-commit run -a`

5 - `git diff` e verificar manualmente as mudanças e ver se está tudo certo

6 - git commit

7 - enjoy...

**Comment by rougeth** [comment]
@luzfcb adicionei um lembrete pra quando for atualizar para 3.10. @muriloviana Obrigado pelo PR!
