### ISSUE TITLE
Cadastrar/Excluir associado do grupo apyb-associados@googlegroups.com

### ISSUE THREAD

**Issue by osantana** [pythonbrasil/associados#88]
Verificar a viabilidade (via API do Google) de inscrever/remover um membro da apyb-associados.com.

**Comment by filipecifali** [comment]
Fechando a issue em resposta retornada pelo @andrewsmedina, se existir alguma forma de criar ela hoje, deve ser reaberta ou aberta uma nova discutindo a implementação para tal.
