### ISSUE TITLE
Fazer o Plone do site associacao.python.org.br autenticar no sistema de associados

### ISSUE THREAD

**Issue by osantana** [pythonbrasil/associados#91]
Acho que pra fazer isso precisamos da ajuda de algum plonista.

Tarefas:
- Ter SSL funcionando em *.python.org.br (comprar o certificado e instalar nos servidores)
- Ter uma API no associados.python.org.br que receba via POST usuário/senha e retorne o status do associado para autenticação
- Atualizar a versão do Plone da APyB (opcional?)
- Plugar o sistema de autenticação no Plone

**Comment by filipecifali** [comment]
Das tarefas, 
SSL é resolvido hoje com Letsencrypt se algum site ainda não tiver podemos criar sem problemas. 
A API será resolvida pela issue #153 
Algum plonista se voluntaria para fazer a tarefa?

**Comment by rougeth** [comment]
Pelo que entendi, todas as tarefas dessa issue foram concluídas, por isso, vou fechá-la. Se faltou algo, podem reabrir. Obrigado!
